### ISSUE TITLE
Find way to incorporate out-of-band reports

### ISSUE THREAD

**Issue by spulec** [unitedstates/inspectors-general#204]
We have created https://github.com/unitedstates/reports as a repository for reports which have been collected outside of this system. We should find a way to incorporate the `inspectors-general` folder there with this project.

Some ideas mentioned here: https://github.com/unitedstates/inspectors-general/issues/185

**Comment by konklone** [comment]
Thank you for getting this started! I think the way to do this is probably a one-off script, maybe `inspectors/manual.py` -- or a `scripts/manual.py` that's called by `./igs` -- to download the repo and walk through them, obeying the `--since` and `--year` flags like everything else. It should integrate cleanly into the system so that they also get backed up in the Internet Archive along with everything else.

**Comment by divergentdave** [comment]
I've been digging into some old 404 errors recently. There are several reports that aren't up where they're supposed to be, but are available elsewhere. (i.e. wayback machine) Should we upload reports that have gone down to this repo and deal with them together?

**Comment by konklone** [comment]
How about to https://github.com/unitedstates/reports? And yeah -- we need to get the internet archive uploader back in sync. It hasn't kept up to date since the last bulk upload.

**Comment by divergentdave** [comment]
Shall we close this after konklone/oversight.garden#76?

**Comment by konklone** [comment]
I edited your PR to use the `Fixes` notation, I believe it will auto-close this once merged, if the same person has commit privileges on both repos...
